"""CustoemerDB to_dict method updated, now it also returns key, value pairs from related models

Revision ID: 85d6b22ae757
Revises: 4a3130ae6dab
Create Date: 2024-03-08 19:34:20.768179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85d6b22ae757'
down_revision = '4a3130ae6dab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
