# For use in development environment
# Build new image
# $ docker-compose up -d --build

version: '3.8'

services:
  web:
    build:
      context: ./checkout-single-subscription
  
    image: united:1.0
    ports:
      - 5001:5000
    env_file:
      - ./checkout-single-subscription/.env.dev
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./checkout-single-subscription/.env.dev

volumes:
  postgres_data:
