# For use in production environment
# https://testdriven.io/blog/dockerizing-flask-with-postgres-gunicorn-and-nginx/#postgres
# https://realpython.com/docker-continuous-integration/#isolate-your-docker-image
# Build new image
# $ docker-compose up -d --build
# $ docker-compose -f docker-compose.prod.yml up -d --build
# NOTE Given port set up on this file, it will only run on Cloud Run
version: '3.8'

services:
  web:
    build:
      context: ./checkout-single-subscription
    command: gunicorn --bind 0.0.0.0:$PORT server:app  # $PORT is set for Gcloud Run
    image: united:1.0-prod
    expose:
      - 5000
    env_file:
      - ./checkout-single-subscription/.env.prod
    depends_on:
      - db
  nginx:
    build:
      context: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
  db:
    image: postgres:16
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./checkout-single-subscription/.env.prod.db
volumes:
  postgres_data_prod:
  